### ISSUE TITLE
Expected results but zero loads 

### ISSUE THREAD

**Issue by MagicGrapix** [MeshFEM/MeshFEM#3]
Hello,

When I'm running the simulation_Cli with a Dirichlet boundary condition and whatever forces I get the expected stresses and displacements but the loads output stays zero. Is this a bug or am I missing something ?

**Comment by jpanetta** [comment]
Without seeing your input I can't say for sure, but if you're using quadratic elements (the default) my guess is this is not a bug but is due to how `Simulate_cli` applies tractions and outputs result fields.

Specifically, tractions are interpreted as piecewise constant fields over the boundary elements. To generate the `load` vector, these are integrated against the FEM shape functions over the boundary. Since the traction is constant over each boundary element, the portion of this integral a given element contributes is actually the constant traction times the integral of the nodes' shape functions over the element. It turns out that for quadratic (P2) elements, the vertex node shape functions integrate to zero over the element, so the load vector entries for vertices are all exactly zero; a constant traction field effectively only places loads on the edge nodes for P2 elements.

Unless you specify `fullDegreeFieldOutput`, only the vertex values of a field are written to the output file, so all nonzero entries of `load` are suppressed.

**Comment by MagicGrapix** [comment]
Hello !

Sorry for the late response. I'm indeed using quadratic elements, I guess it is equivalent to say tetrahedrons ? (I'm new to FEM :)). I found a workaround for the loads. Have a missed a documentation for you library ? I haven't seen the `fullDegreeFieldOutput` field in the github page, is it a parameter of Simulate_Cli ? By the way the library is working quite nicely. Keep up the good job !

Best,

**Comment by jpanetta** [comment]
The shape function degree (linear vs quadratic) is a separate issue from whether you're using tetrahedra (you can use linear or quadratic tetrahedra; the quadratic simulation used by default is more accurate though more expensive for a given tet mesh resolution).

The documentation for the binaries is quite incomplete (as is really all the documentation). In fact, they probably never will be documented since I'm planning to phase them out in favor of a Python interface. But in the meantime you can get a full list and description of the arguments accepted by any of the binaries (including `Simulate_cli`) by running them with no arguments.

**Comment by MagicGrapix** [comment]
Okay, yeah I saw. And the source code is quite understandable too. I think this issue can be closed, thanks !
