### ISSUE TITLE
CHOLMOD detected non-positive definite matrix!

### ISSUE THREAD

**Issue by MagicGrapix** [MeshFEM/MeshFEM#5]
Hello, 

I have now this error "CHOLMOD detected non-positive definite matrix!". The first time I was getting it was because some elements in my model were having negatives volumes (if I'm not mistaken) and I used the script to reorient them with mesh_convert. But I still get this error for some models. What can be the cause otherwise ? 

Thanks for the support.
Best

**Comment by jpanetta** [comment]
There are several things that can cause this, and without seeing your input files it's impossible to say. A couple likely explanations: your boundary conditions might not include enough Dirichlet constraints to pin down the object's rigid motion, making the equilibrium problem underdetermined (and thus the linear system singular/non-positive definite). Or maybe your mesh has multiple components--e.g., if its vertices are not glued together properly--that are not each individually fixed in space by Dirichlet constraints.
